# Generated by Django 3.2.7 on 2021-09-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20210917_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='private_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='public_key',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
