# Generated by Django 3.2.7 on 2021-09-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_fiat_transactions_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiat_details',
            old_name='user',
            new_name='users',
        ),
    ]
