# Generated by Django 3.2.7 on 2021-10-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_reviews_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiat_details',
            name='account_number',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='fiat_details',
            name='bank_details',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
