# Generated by Django 3.2.7 on 2021-10-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20211029_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiat_details',
            name='account_name',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
