# Generated by Django 3.2.7 on 2021-09-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_rename_users_fiat_details_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiat_transactions',
            name='transaction_type',
            field=models.CharField(choices=[('Withdrawal', 'Withdrawal'), ('Deposit', 'Deposit'), ('Buy', 'Buy'), ('Sell', 'Sell')], max_length=10),
        ),
    ]
