# Generated by Django 3.2.7 on 2021-09-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_fiat_transactions_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiat_transactions',
            name='userid',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
